overblog_graphql:
    definitions:
        schema:
            skills:
              query: Query
              mutation: Mutation
            testing:
              query: TestingQueries
              mutation: TestingMutations
        mappings:
            types:
                - type: yaml
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: null
                - type: attribute
                  dir: "%kernel.project_dir%/src"
                  suffix: ~
    errors_handler:
      map_exceptions_to_parent: false
      exceptions:
        errors:
          - "Webmozart\\Assert\\InvalidArgumentException"