Query:
  type: object
  config:
    description: "Запросы модуля навыков."
    fields:

      findSkillById:
        type: "Skill"
        description: "Найти навык по идентификатору."
        args:
          id:
            description: "ID навыка"
            type: "String!"
        resolve: "@=query('findSkillById', args['id'])"

      findSkillGroupById:
        type: "SkillGroup"
        description: "Найти группу навыков по идентификатору."
        args:
          id:
            description: "ID групп навыков"
            type: "String!"
        resolve: "@=query('findSkillGroupById', args['id'])"

      paginateSkillGroups:
        type: "[SkillGroup]"
        description: "Постраничный список групп навыков."
        args:
          input:
            description: "Фильтр групп навыков"
            type: "SkillGroupsFilter!"
        resolve: "@=query('paginateSkillGroups', arguments({input: 'SkillGroupsFilter'}, args)[0], info)"