TestingMutations:
  type: object
  config:
    description: "Мутации модуля тестирования."
    fields:

      createTest:
        type: "TestingTest"
        description: "Создать тест."
        resolve: "@=mutation('createTest', args['name'], args['description'], args['difficultyLevel'], args['correctAnswersPercentage'], args['skillId'])"
        args:
          name:
            type: "String!"
          description:
            type: "String!"
          difficultyLevel:
            type: "TestingDifficultyLevel!"
          correctAnswersPercentage:
            type: "Int!"
          skillId:
            type: "String"

      createQuestion:
        type: "TestingQuestion"
        description: "Создать вопрос теста."
        resolve: "@=mutation('createQuestion', args['name'], args['description'], args['type'], args['testId'])"
        args:
          name:
            type: "String!"
          description:
            type: "String!"
          type:
            type: "TestingQuestionType!"
          testId:
            type: "String!"

      createAnswerOption:
        type: "TestingAnswerOption"
        description: "Создать вариант ответа на вопрос теста."
        resolve: "@=mutation('createAnswerOption', args['questionId'], args['description'], args['isCorrect'])"
        args:
          questionId:
            type: "String!"
          description:
            type: "String!"
          isCorrect:
            type: "Boolean!"