services:
  _defaults:
    autowire: true

  App\Tests\Resource\Fixture\:
    resource: '%kernel.project_dir%/tests/Resource/Fixture/*'
    tags:
      - { "name": "doctrine.fixture.orm" }

  App\Shared\Infrastructure\Bus\CommandBus:
    public: true

  App\Shared\Infrastructure\Bus\QueryBus:
    public: true

  App\Shared\Infrastructure\Bus\EventBus:
    public: true

  # PUBLIC SERVICES

  App\*\Domain\Specification\:
    namespace: App\
    public: true
    resource: '../src/*/Domain/Specification'
    exclude: '../src/Shared/*'

  App\*\Domain\Factory\:
    namespace: App\
    public: true
    resource: '../src/*/Domain/Factory'
    exclude: '../src/Shared/*'